#!/bin/bash

# For when you have a container with influx
INFLUX_CONTAINER_NAME=dashboard-influxdb

echo "exporting to line format..."
unzip -p $1 All*.csv | python hobolinkcsv2line.py | gzip > import.influx.gz

echo "copying to container..."
docker cp import.influx.gz ${INFLUX_CONTAINER_NAME}:/tmp
echo "importing..."
docker exec -it ${INFLUX_CONTAINER_NAME} influx -import -compressed -precision=s -path=/tmp/import.influx.gz 

#rm import.influx.gz